---
- name:           add the oracle java ppa
  apt_repository: repo='ppa:webupd8team/java'

- name:           accept Oracle license
  shell:          "echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections"

- name:           ensure that the java8 installer is at the latest version
  apt:            name=oracle-java8-installer state=latest install_recommends=yes update_cache=yes
